### PR TITLE
Actual soil moisture conversion

### LINKED ISSUE #138: Implement the actual conversion process using the mapper

### LINKED ISSUE #160: Conversion model name in meta
Meta should only contain the conversion model name and not the id.

### PR DESCRIPTION
**Pull request by BioBoost**
- Add type of measurement sample
- Implement basic linear interpolation conversion model
- Convert last_value and values using conversion model when applicable. This closes #138, closes #160

### CODE REVIEW

**Review by noahdebaere — CHANGES_REQUESTED** [review]
ConversionModels not implemented in the find method called by /trees

**Comment by BioBoost** [comment]
This should be ok now.

**Comment by Phasmatrix** [comment]
Everything looks good, will have to change my postman runners to work again with updates. Was not able to test completely due to the fact that my postman runner did not create all devices. Will finish this tomorrow.

**Review by Phasmatrix — APPROVED** [review]

**Comment by Phasmatrix** [comment]
Doublechecked everything and it works as expected.

**Pull request merged**
